DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typname = 'AdminUserStatus' AND n.nspname = current_schema()) THEN
        CREATE TYPE "AdminUserStatus" AS ENUM ('REGISTERED', 'OTP_PENDING', 'ADMIN_APPROVAL_PENDING', 'ACTIVE', 'REJECTED');
    END IF;
END$$;

ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "status" "AdminUserStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "isEmailVerified" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "isMobileVerified" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "isApprovedByAdmin" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "requestedRole" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "companyName" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "companyDetails" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "otpAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "otpLastSentAt" TIMESTAMP(3);
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "otpVerifiedAt" TIMESTAMP(3);
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3);
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
