export const CITY_TO_STATE_MAP: Record<string, string> = {
  bengaluru: "Karnataka",
  bangalore: "Karnataka",
  hyderabad: "Telangana",
  pune: "Maharashtra",
  mumbai: "Maharashtra",
  chennai: "Tamil Nadu",
  delhi: "Delhi",
  gurgaon: "Haryana",
  gurugram: "Haryana",
  noida: "Uttar Pradesh",
  kolkata: "West Bengal",
  ahmedabad: "Gujarat",
  jaipur: "Rajasthan",
  coimbatore: "Tamil Nadu",
  kochi: "Kerala",
  ernakulam: "Kerala",
  indore: "Madhya Pradesh",
  surat: "Gujarat",
  bhubaneswar: "Odisha",
};

export const DEFAULT_STATE = "Karnataka";
export const DEFAULT_CITY = "Bengaluru";

export const DEFAULT_PAGE_SIZE = 10;

export const INDIA_STATES_AND_UTS: readonly string[] = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const TAB_ITEMS = [
  { key: "techParks" as const, label: "Tech Parks" },
  { key: "coworkingSpaces" as const, label: "Coworking Spaces" },
];

export const DEFAULT_NEW_LOCATION = {
  id: "",
  name: "",
  address: "",
  website: "",
  operator: "",
  description: "",
  rating: 0,
  total_ratings: 0,
  business_status: "OPERATIONAL",
  phone: "",
  map_url: "",
  opening_hours: "",
  locationLat: "",
  locationLng: "",
  lat: null,
  lng: null,
  status: "NOT_CONTACTED",

  builder_name: "",
  security_agency_name: "",
  property_manager_name: "",
  property_manager_phone: "",
  property_manager_email: "",
  parking_floors: 0,
  total_floors: 0,
  basement_levels: 0,
  spoc_name: "",
  spoc_phone: "",
  seating_capacity: 0,
  challenges: "",
  coordinates: "",
  exterior_media_url: "",
  exterior_media_urls: [] as string[],
  generic_email: "",
  campus_size_hint: "",
  district: "",
  pincode: "",
}; 
